package com.opportunityboard.application.dto.opportunity;

import com.opportunityboard.application.dto.document.DocumentResponse;
import com.opportunityboard.domain.enums.*;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record OpportunityDetailResponse(
        UUID oppId,
        UUID orgId,
        String title,
        String slug,
        String orgName,
        String logoUrl,
        String bannerUrl,
        String orgDescription,
        String orgWebsite,
        String orgContactEmail,
        String orgContactPhone,
        String orgTaxCode,
        String orgAddress,
        String orgIndustry,
        CompanySize orgCompanySize,
        String categoryCode,
        String categoryName,
        String description,
        String requirements,
        String benefits,
        String salaryOrReward,
        Long salaryMin,
        Long salaryMax,
        String salaryCurrency,
        boolean salaryNegotiable,
        String selectionProcess,
        JobLevel jobLevel,
        ExperienceLevel experienceLevel,
        EducationLevel educationLevel,
        Integer headcount,
        EmploymentType employmentType,
        String addressDetail,
        String workingSchedule,
        String skills,
        LocationType location,
        WorkType workType,
        ApplyMode applyMode,
        String externalLink,
        Instant deadline,
        OppStatus storedStatus,
        Instant publishedAt,
        boolean isFeatured,
        int viewCount,
        int bookmarkCount,
        int applicationCount,
        int shareCount,
        List<UUID> domainIds,
        List<OpportunityResponse> related,
        List<DocumentResponse> documents
) {}
